total_iters: 30000
output_dir: /content/gdrive/My Drive/img_style/PaddleGAN/output_dir/starry_patch/
checkpoints_dir: checkpoints
min_max:
  (0., 1.)

model:
  name: LapStyleDraXDOG
  generator_encode:
    name: Encoder
  generator_transformer:
    name: DecoderQuantized
  discriminator:
    name: LapStyleSingleDiscriminator
    num_channels: 64
    num_layer: 5
    noise: 0
    kernel_size: 3
    padding: 1
  calc_style_emd_loss:
    name: CalcStyleEmdLoss
  calc_content_relt_loss:
    name: CalcContentReltLoss
  calc_content_loss:
    name: CalcContentLoss
  calc_style_loss:
    name: CalcStyleLoss
  mse_loss:
    name: GramErrors
  gan_criterion:
    name: GANLoss
    gan_mode: vanilla
  content_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  style_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  content_weight: 1
  style_weight: 5
  morph_cutoff: 8.85
  gamma: .9


dataset:
  train:
    name: LapStyleDataset
    content_root: /content/gdrive/My Drive/img_style/cocostuff/dataset/img/train2017/
    style_root: /content/gdrive/My Drive/img_style/styles_small/
    load_size: 128
    style_upsize: 1
    crop_size: 128
    num_workers: 16
    batch_size: 5
  test:
    name: LapStyleThumbsetInference
    content_root: /content/gdrive/My Drive/img_style/washnight/
    style_root: /content/PaddleGAN/starrypatched1024.png
    load_size: 128
    crop_size: 128
    thumb_size: 128
    patch_depth: 1
    style_upsize: 1
    num_workers: 0
    batch_size: 1

lr_scheduler:
  name: WarmupNonLinear
  learning_rate: 1e-4
  lr_decay: 5e-5
  warmupstart: 1e-9
  warmupperiod: 5000

optimizer:
  optimG:
    name: Adam
    net_names:
      - net_vit
    beta1: 0.9
    beta2: 0.999
    weight_decay: .1
  optimD:
    name: Adam
    net_names:
      - netD
    beta1: 0.9
    beta2: 0.999
    weight_decay: .1

validate:
  interval: 100000
  save_img: false

log_config:
  interval: 10
  visiual_interval: 50

snapshot_config:
  interval: 2500
