total_iters: 100000
output_dir: /content/gdrive/My Drive/img_style/PaddleGAN/output_dir/starry/
checkpoints_dir: checkpoints
min_max:
  (0., 1.)

model:
  name: LapStyleRevSecondPatch
  revnet_generator:
    name: RevisionNetThumb
  revnet_discriminator:
    name: LapStyleDiscriminator
    num_channels: 32
  draftnet_encode:
    name: Encoder
  draftnet_decode:
    name: DecoderNet
  revnet_deep_generator:
    name: RevisionNetDeepThumb
  calc_style_emd_loss:
    name: CalcStyleEmdLoss
  calc_content_relt_loss:
    name: CalcContentReltLoss
  calc_content_loss:
    name: CalcContentLoss
  calc_style_loss:
    name: CalcStyleLoss
  gan_criterion:
    name: GANLoss
    gan_mode: vanilla
  content_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  style_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  content_weight: 1
  style_weight: 6

dataset:
  train:
    name: MultiPatchSet
    content_root: /content/gdrive/My Drive/img_style/large_pics/
    style_root: /content/PaddleGAN/starrypatched2048.png
    load_size: 2048
    crop_size: 256
    thumb_size: 256
    patch_depth: 4
    style_upsize: 1.1
    num_workers: 16
    batch_size: 2
  test:
    name: LapStyleThumbsetInference
    content_root: /content/gdrive/My Drive/img_style/test_inference/
    style_root: /content/PaddleGAN/starrypatched2048.png
    load_size: 2048
    crop_size: 256
    thumb_size: 256
    style_upsize: 1
    patch_depth: 4
    num_workers: 0
    batch_size: 1

lr_scheduler:
  name: NonLinearDecay
  learning_rate: 2e-4
  lr_decay: 5e-5

optimizer:
  optimG:
    name: Adam
    net_names:
      - net_rev_2
    beta1: 0.9
    beta2: 0.999
  optimD:
    name: Adam
    net_names:
      - netD
    beta1: 0.9
    beta2: 0.999
  optimD_patch:
    name: Adam
    net_names:
      - netD_patch
    beta1: 0.9
    beta2: 0.999

validate:
  interval: 100000
  save_img: false

log_config:
  interval: 10
  visiual_interval: 100

snapshot_config:
  interval: 1000
