total_iters: 200000
output_dir: /content/gdrive/My Drive/img_style/PaddleGAN/output_dir/vangogh_starry/
checkpoints_dir: checkpoints
min_max:
  (0., 1.)

model:
  name: LapStyleDraXDOG
  generator_encode:
    name: Encoder
  generator_transformer:
    name: ViT
    image_size: 128
    patch_size: 8
    channels: 6
    num_classes: 1000
    dim: 1024
    depth: 6
    pool: cls
    heads: 16
    mlp_dim: 2048
    dropout: 0
    emb_dropout: 0
  calc_style_emd_loss:
    name: CalcStyleEmdLoss
  calc_content_relt_loss:
    name: CalcContentReltLoss
  calc_content_loss:
    name: CalcContentLoss
  calc_style_loss:
    name: CalcStyleLoss
  gram_errors:
    name: GramErrors
  content_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  style_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  content_weight: 1
  style_weight: 1
  morph_cutoff: 8.85
  gamma: .9


dataset:
  train:
    name: LapStyleDataset
    content_root: /content/gdrive/My Drive/img_style/cocostuff/dataset/img/train2017/
    style_root: /content/PaddleGAN/cypresssmall.png
    load_size: 128
    crop_size: 128
    style_upsize: 1
    num_workers: 16
    batch_size: 1
  test:
    name: LapStyleDataset
    content_root: /content/gdrive/My Drive/img_style/cocostuff/dataset/img/train2017/
    style_root: /content/gdrive/My Drive/img_style/styles/
    load_size: 128
    crop_size: 128
    thumb_size: 128
    num_workers: 0
    batch_size: 1

lr_scheduler:
  name: WarmupNonLinear
  learning_rate: 1e-4
  lr_decay: 1e-5
  warmupstart: 1e-8
  warmupperiod: 1000

optimizer:
  optimG:
    name: Adam
    net_names:
      - net_vit
    beta1: 0.9
    beta2: 0.999
validate:
  interval: 150000
  save_img: false

log_config:
  interval: 10
  visiual_interval: 100

snapshot_config:
  interval: 10000
