total_iters: 100000
output_dir: /content/gdrive/My Drive/img_style/PaddleGAN/output_dir/vangogh_starry/
checkpoints_dir: checkpoints
min_max:
  (0., 1.)

model:
  name: LapStyleRevSecondMXDOG
  revnet_generator:
    name: RevisionNetDeepThumb
  revnet_discriminator_1:
    name: LapStyleSingleDiscriminator
    num_channels: 64
    num_layer: 5
    kernel_size: 3
    padding: 1
  revnet_discriminator_2:
    name: LapStyleSingleDiscriminator
    num_channels: 64
    num_layer: 5
    kernel_size: 7
    padding: 3
  revnet_discriminator_3:
    name: LapStyleSingleDiscriminator
    num_channels: 64
    num_layer: 7
    kernel_size: 7
    padding: 3
  revnet_discriminator_4:
    name: LapStyleSingleDiscriminator
    num_channels: 64
    num_layer: 9
    kernel_size: 7
    padding: 3
  spectral_discriminator:
    name: LapStyleSpectralDiscriminator
    num_channels: 64
    num_layer: 4
    kernel: 7
    padding: 3
  draftnet_encode:
    name: Encoder
  draftnet_decode:
    name: DecoderNetDeep
  revnet_deep_generator:
    name: RevisionNetThumb
  calc_style_emd_loss:
    name: CalcStyleEmdLoss
  calc_content_relt_loss:
    name: CalcContentReltLoss
  calc_content_loss:
    name: CalcContentLoss
  calc_style_loss:
    name: CalcStyleLoss
  mse_loss:
    name: GramErrors
  gan_criterion:
    name: GANLoss
    gan_mode: vanilla
  content_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  style_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  content_weight: 1
  style_weight: 3.5
  train_layer: 2
  train_spectral: 1
  ada_alpha: .05
  ada_alpha_2: .05
  gan_thumb_weight: 1
  gan_patch_weight: 2
  use_mdog: 1
  morph_cutoff: 8.5

dataset:
  train:
    name: MultiPatchSet
    content_root: /content/gdrive/My Drive/img_style/cocostuff/dataset/img/train2017/
    style_root: /content/PaddleGAN/cypress512.png
    load_size: 512
    crop_size: 256
    thumb_size: 256
    patch_depth: 1
    style_upsize: 1
    num_workers: 8
    batch_size: 4
  test:
    name: LapStyleThumbsetInference
    content_root: /content/gdrive/My Drive/img_style/inference_test/
    style_root: /content/PaddleGAN/starrypatched2048.png
    load_size: 2048
    crop_size: 256
    thumb_size: 256
    style_upsize: 1
    patch_depth: 4
    num_workers: 0
    batch_size: 1

lr_scheduler:
  name: NonLinearDecay
  learning_rate: 1e-4
  lr_decay: 5e-5

optimizer:
  optimG1:
    name: Adam
    net_names:
      - net_rev
    beta1: 0.9
    beta2: 0.999
  optimG2:
    name: Adam
    net_names:
      - net_rev_2
    beta1: 0.9
    beta2: 0.999
  optimD1:
    name: Adam
    net_names:
      - netD_1
    beta1: 0.9
    beta2: 0.999
  optimD2:
    name: Adam
    net_names:
      - netD_2
    beta1: 0.9
    beta2: 0.999
  optimSD:
    name: Adam
    net_names:
      - spectral_D
    beta1: 0.9
    beta2: 0.999
validate:
  interval: 100000
  save_img: false

log_config:
  interval: 10
  visiual_interval: 50

snapshot_config:
  interval: 1000
