total_iters: 100000
output_dir: /content/gdrive/My Drive/img_style/PaddleGAN/output_dir/starry/
checkpoints_dir: checkpoints
min_max:
  (0., 1.)

model:
  name: LapStyleDraModel
  generator_encode:
    name: Encoder
  generator_decode:
    name: DecoderNet
  calc_style_emd_loss:
    name: CalcStyleEmdLoss
  calc_content_relt_loss:
    name: CalcContentReltLoss
  calc_content_loss:
    name: CalcContentLoss
  calc_style_loss:
    name: CalcStyleLoss
  content_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  style_layers: ['r11', 'r21', 'r31', 'r41', 'r51']
  content_weight: 2.3
  style_weight: 5


dataset:
  train:
    name: LapStyleDataset
    content_root: /content/gdrive/My Drive/img_style/cocostuff/dataset/img/train2017/
    style_root: /content/PaddleGAN/starrypatched1024.png
    load_size: 132
    crop_size: 128
    style_upsize: 1.25
    num_workers: 16
    batch_size: 5
  test:
    name: LapStyleDataset
    content_root: /content/gdrive/My Drive/img_style/washnight/
    style_root: /content/PaddleGAN/starrypatched1024.png
    load_size: 128
    crop_size: 128
    thumb_size: 128
    num_workers: 0
    batch_size: 1

lr_scheduler:
  name: NonLinearDecay
  learning_rate: 1e-4
  lr_decay: 5e-5

optimizer:
  optimG:
    name: Adam
    net_names:
      - net_dec
    beta1: 0.9
    beta2: 0.999

validate:
  interval: 40000
  save_img: false

log_config:
  interval: 10
  visiual_interval: 100

snapshot_config:
  interval: 1250
